server:
  port: 8106

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_flowable?serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: Ab123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# flowable相关表
flowable:
  # 默认为true 会对数据库中所有表进行更新操作。如果表不存在，则自动创建(建议开发时使用)
  database-schema-update: true
  # 默认为true，false表示关闭定时任务JOB
  async-executor-activate: false